### ISSUE TITLE
Task: Update Shipit to latest version

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-shipit#189]
Shipit is a few version behind
We can use [this pull request](https://github.com/bcgov/cas-shipit/pull/158) to mirror the upgrade process

**Comment by dleard** [comment]
@mikevespi We are a few versions behind again. Let's upgrade shipit

**Comment by patriciarussellCAS** [comment]
@joshgamache - not sure if this is something you can support with? Tagging for visibility.

**Comment by pbastia** [comment]
Duplicate of #210
