### ISSUE TITLE
Tech Debt: Increase resources request for Shipit

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-shipit#203]
Shipit gets increasingly slow, we can easily double the resource request on the cluster

**Comment by pbastia** [comment]
@LindsayMacfarlane shipit is getting more use now that we're doing releases and deployments on multiple apps at the same time, and that will likely be the case for the next quarter. I suggest putting this in the next sprint, it's an easy one and a good learning opportunity for devops

**Comment by LindsayMacfarlane** [comment]
Thanks for flagging @pbastia - I've pulled into the next sprint backlog for team discussion during tomorrow's sprint planning.

**Comment by patriciarussellCAS** [comment]
@pbastia is this complete or do we still need to increase resources here.

**Comment by pbastia** [comment]
This is complete!
