### ISSUE TITLE
Tech Debt: update shipit

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-shipit#210]
Shipit is a relatively old installation, it would be beneficial to the team to figure out how to maintain it and upgrade it

**Comment by patriciarussellCAS** [comment]
Moved to backlog until we know whether or not we're keeping Ship-it or moving to something else. 
To confirm: create new card for exploration of other options.

**Comment by pbastia** [comment]
I think I have a relatively easy upgrade path for this one.
The Helm chart is not too out-of-date and would only need minor tweaks, the main changes would be to update the docker image and configuration files.

**Comment by pbastia** [comment]
@patriciarussellCAS you can verify this by logging into shipit and checking that the version number is now 0.39.0!
